name: Deploy to FTP (Safe Mode)

on:
  push:
    branches:
      - main   # sadece main branch push edilince çalışır

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          local-dir: ./                # GitHub’daki kök klasör
          server-dir: /httpdocs/       # FTP’deki hedef klasör
          dangerous-clean-slate: false #  extra dosyaları silmez
          log-level: verbose
          exclude: |
            /icerik/bolgpt.php 
            /icerik/bolgptnb.php
